### ISSUE TITLE
No issue. Just read plz. 

### ISSUE THREAD

**Issue by LordJoshie** [Infernus101/PowerFactions#4]
If you haveKik Msgr or Email,  Kik- Dark.Miner    Email- jawshawa.p@gmail.com

Plz msg me.

**Comment by Infernus101** [comment]
Why?

**Comment by LordJoshie** [comment]
ugh... there, 35 stars. release the Economy update :) 

And email me plz. 

I'm not a kid dude. I'm 26, I have something about ur plug to tell u.

**Comment by Infernus101** [comment]
ok, it just supports EconomyAPI

**Comment by daniktheboss** [comment]
I will use this plugin! Thanks for it! But now I have to wait for my factions to reset... 1 week left XD
