### ISSUE TITLE
SUGGESTION .. NOT AN ACTUAL ISSUE

### ISSUE THREAD

**Issue by starterdragon** [Infernus101/PowerFactions#5]
Suggestion: Make a Command where OP and Console are the only one who can use..

/f btop (/faction broadcasttop)
- It will Broadcast TOP Factions to all players, this is good for events, and for plugins like TimeCommander.. Thanks..
- and If you somehow consider this, please just use the name and number of players, to make it up to 10.. and to avoid long messages *winks* thanks ! nice Plugin tho.

**Comment by Infernus101** [comment]
what do u mean by number of players 10? like 10 players in a faction? or 10 top factions?

**Comment by daniktheboss** [comment]
Also make that u can do /f (playername) and it give you the faction name! Pleaseee

**Comment by daniktheboss** [comment]
I mean players faction name

**Comment by Adam1609** [comment]
If broadcasting may be confusing! Just leave it that way, and by the way, @Infernus101 your plugin is cool :D

**Comment by Infernus101** [comment]
I m already doing that @daniktheboss

**Comment by Infernus101** [comment]
and thanks @Adam1609

**Comment by Adam1609** [comment]
@Infernus101 I will alway remember the time I help you with pureperm :D

**Comment by Infernus101** [comment]
@Adam1609 yea lol!
