### ISSUE TITLE
/f members bug and /f claim

### ISSUE THREAD

**Issue by starterdragon** [Infernus101/PowerFactions#7]
/f claim has a bug where even if you are an Officer or a Leader, once OfficerCanClaim = true,
you will only receive "Only Leaders and Officers can claim".

/f members update seems doesn't work from the first one.
/f mem is the first issued /f members command.
![image](https://cloud.githubusercontent.com/assets/16812043/16716199/8c78f1fc-4728-11e6-83ef-728498990672.png)

**Comment by Adam1609** [comment]
Disable OfficerCanClaim, that bug may be fixed :)

**Comment by Infernus101** [comment]
Fixed! Also added /f search <name>
